LoBSTr: &DEFAULT
  training_set: dataset_LoBSTr_60fps_train_noised_0.005_1.npz
  valid_set: dataset_LoBSTr_60fps_valid_noised_0.005_1.npz

  lr: 1.0e-3
  lr_decay: 0.999
  num_epochs: 3000

  window_size: 60
  model: LoBSTr_GRU

  # in out hidden latent
  net_params: [ 37, 48, 1024, 256 ]
  batch_size: 256

  loss_hparams: [ 1.0, 1.0e-1, 1.0e-1, 1.0e-6 ]

  optimizer: Adam