EG2021: &DEFAULT
  training_set: dataset_EG2021_60fps_train.npz
  valid_set: dataset_EG2021_60fps_valid.npz

  lr: 1.0e-2
  lr_decay: 0.99
  num_epochs: 1500

  window_size: 60
  model: LoBSTr_GRU

  # in out hidden latent
  net_params: [64, 96, 1024, 256]
  batch_size: 8

  loss_hparams: [1, 0.1, 0.1, 1.0e-6]

  optimizer: Adam


TestConfig:
  training_set: dataset_EG2021_60fps.npz
  valid_set: dataset_EG2021_60fps.npz

  lr: 1.0e-5
  lr_decay: 0.99
  num_epochs: 1500

  window_size: 60
  model: LoBSTr_GRU

  # in out hidden latent
  net_params: [64, 96, 1024, 256]
  batch_size: 2

  loss_hparams: [1, 0.1, 0.1, 1.0e-6]

  optimizer: Adam