EG2021: &DEFAULT
  training_set: dataset_EG2021_60fps.npz
  valid_set: dataset_EG2021_60fps.npz

  lr: 1e-3
  lr_decay: 0.999
  num_epochs: 1500

  window_size: 60
  model: LoBSTr_GRU

  # in out hidden latent
  net_params: [64, 96, 1024, 256]
  batch_size: 32

  loss_hparams: [1, 0.1, 0.1, 1.0e-6]

  optimizer: Adam
